framework:
  - terraform
quiet: true
compact: true

# Skip checks that are deployment-specific or have acceptable workarounds
skip-check:
  # Storage Account Security - These are configured for deployment access
  # In production, these should be reviewed and hardened based on specific requirements
  - CKV_AZURE_226  # Disable public network access to storage account
  - CKV_AZURE_59   # Storage account should restrict network access
  - CKV_AZURE_35   # Ensure default network access rule for Storage Accounts is set to deny
  - CKV2_AZURE_40  # Ensure storage account is not configured with Shared Key authorization
  
  # AKS Security Configuration
  - CKV_AZURE_109  # Ephemeral OS disks (configured with supported VM size)
  - CKV_AZURE_6    # AKS API server authorized IP ranges (incompatible with private cluster)
  - CKV_AZURE_227  # Host encryption (requires subscription feature enablement)
  
  # Storage Account Customer Managed Keys (disabled for development deployment)
  - CKV2_AZURE_1   # Customer managed key encryption (using Microsoft managed keys for dev)
  - CKV_AZURE_112  # HSM protected keys (simplified for development)
  
  # Key Vault Security - Network access rules for deployment
  - CKV2_AZURE_32  # Ensure private endpoint connections on Key Vault
  
  # Queue logging is enabled via Azure CLI in null_resource
  # This is necessary because Terraform AzureRM provider doesn't support
  # Storage Analytics queue logging configuration directly
  - CKV_AZURE_33
  
  # Storage account naming follows Azure rules but may not match Checkov's stricter pattern
  # Our naming ensures uniqueness and follows: lowercase alphanumeric, 3-24 chars, globally unique
  - CKV_AZURE_43
