framework:
  - terraform
quiet: true
compact: true

# Skip checks that are deployment-specific or have acceptable workarounds
skip-check:
  # Storage Account Security - These are configured for deployment access
  # In production, these should be reviewed and hardened based on specific requirements
  - CKV_AZURE_226  # Disable public network access to storage account
  - CKV_AZURE_59   # Storage account should restrict network access
  - CKV_AZURE_35   # Ensure default network access rule for Storage Accounts is set to deny
  - CKV2_AZURE_40  # Ensure storage account is not configured with Shared Key authorization
  
  # AKS Node Pool Security - Ephemeral disks require specific VM sizes
  # CKV_AZURE_109: This check requires ephemeral OS disks which are only supported
  # on specific VM SKUs. We're using supported SKUs but the check may still flag.
  - CKV_AZURE_109
  
  # Key Vault Security - Network access rules for deployment
  - CKV2_AZURE_32  # Ensure private endpoint connections on Key Vault
  
  # Queue logging is enabled via Azure CLI in null_resource
  # This is necessary because Terraform AzureRM provider doesn't support
  # Storage Analytics queue logging configuration directly
  - CKV_AZURE_33
  
  # Storage account naming follows Azure rules but may not match Checkov's stricter pattern
  # Our naming ensures uniqueness and follows: lowercase alphanumeric, 3-24 chars, globally unique
  - CKV_AZURE_43
