name: "Debug Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-validation:
    name: "Test Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Simple test
        run: echo "✅ Validation works"

  test-plan:
    name: "Test Plan"
    runs-on: ubuntu-latest
    needs: test-validation
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simple test
        run: echo "✅ Plan works"

  test-deploy:
    name: "Test Deploy"
    runs-on: ubuntu-latest
    needs: [test-validation, test-plan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Simple test
        run: echo "✅ Deploy works"
